apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-echo
spec:
  replicas: 3
  serviceName: sts-echo
  selector:
    matchLabels:
      app: sts-echo
  template:
    metadata:
      labels:
        app: sts-echo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sts-echo-pod
        image: k8s.gcr.io/echoserver:1.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sts-echo
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: webport
      port: 9000
      targetPort: 8080
  selector:
    app: sts-echo
