Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20220423.0.0"
  config.vm.provision "shell", inline: "sudo apt update"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.network "forwarded_port", guest: 22, host: 60510, auto_correct: true, id: "ssh"
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |spec|
    spec.memory = "2048"
    spec.cpus = "2"
    spec.linked_clone = true
  end
end
