apiVersion: v1
kind: Pod
metadata:
  name: pod0
  labels:
    app: pod
spec:
  nodeName: k8s-w0
  containers:
  - name: netshoot-pod
    image: nicolaka/netshoot
    command: ["tail"]
    args: ["-f", "/dev/null"]
  terminationGracePeriodSeconds: 0