Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20220423.0.0"
  config.vm.provision "shell", inline: "echo 'sudo su -' >> .bashrc"
  config.vm.provision "shell", inline: "apt update"
  config.vm.provision "shell", inline: "curl -fsSL https://get.docker.com | sh"
  config.vm.provision "shell", inline: "apt install -y bridge-utils net-tools jq tree "
  config.vm.synced_folder "./", "/vagrant", disabled: true

  config.vm.define "docker" do |vm1|
    vm1.vm.hostname = "docker" 
    vm1.vm.network "private_network", ip: "192.168.50.10"
    vm1.vm.network "forwarded_port", guest: 22, host: 60610, auto_correct: true, id: "ssh"
    vm1.vm.provider :virtualbox do |spec|
      spec.cpus = 2
      spec.memory = 2048
      spec.name = "docker"
      spec.linked_clone = true
    end
  end
end
